//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calling code is universally portable but the referenced API is only supported for a specific set of platforms..
        /// </summary>
        internal static string PC0001Description {
            get {
                return ResourceManager.GetString("PC0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is only supported on {1}..
        /// </summary>
        internal static string PC0001MessageFormat {
            get {
                return ResourceManager.GetString("PC0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used API isn&apos;t universally portable.
        /// </summary>
        internal static string PC0001Title {
            get {
                return ResourceManager.GetString("PC0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced API isn&apos;t portable to all the platforms supported by the caling code..
        /// </summary>
        internal static string PC0002Description {
            get {
                return ResourceManager.GetString("PC0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not supported on {1}..
        /// </summary>
        internal static string PC0002MessageFormat {
            get {
                return ResourceManager.GetString("PC0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used API is less portable than the calling code..
        /// </summary>
        internal static string PC0002Title {
            get {
                return ResourceManager.GetString("PC0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API throws PlatformNotSupportedException for some platforms and thus should be marked as platform-specific..
        /// </summary>
        internal static string PC0003Description {
            get {
                return ResourceManager.GetString("PC0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; isn&apos;t supported on {1} but isn&apos;t marked as such..
        /// </summary>
        internal static string PC0003MessageFormat {
            get {
                return ResourceManager.GetString("PC0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API should be declared as platform-specific.
        /// </summary>
        internal static string PC0003Title {
            get {
                return ResourceManager.GetString("PC0003Title", resourceCulture);
            }
        }
    }
}
